/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package webservice;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-05-14")
public class Student implements org.apache.thrift.TBase<Student, Student._Fields>, java.io.Serializable, Cloneable, Comparable<Student> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Student");

  private static final org.apache.thrift.protocol.TField FIRST_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("firstName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField SECOND_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("secondName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField NUMBER_COURSE_FIELD_DESC = new org.apache.thrift.protocol.TField("numberCourse", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField NUMBER_GROUP_FIELD_DESC = new org.apache.thrift.protocol.TField("numberGroup", org.apache.thrift.protocol.TType.I64, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new StudentStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new StudentTupleSchemeFactory();

  public java.lang.String firstName; // required
  public java.lang.String secondName; // required
  public long numberCourse; // required
  public long numberGroup; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FIRST_NAME((short)1, "firstName"),
    SECOND_NAME((short)2, "secondName"),
    NUMBER_COURSE((short)3, "numberCourse"),
    NUMBER_GROUP((short)4, "numberGroup");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FIRST_NAME
          return FIRST_NAME;
        case 2: // SECOND_NAME
          return SECOND_NAME;
        case 3: // NUMBER_COURSE
          return NUMBER_COURSE;
        case 4: // NUMBER_GROUP
          return NUMBER_GROUP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __NUMBERCOURSE_ISSET_ID = 0;
  private static final int __NUMBERGROUP_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FIRST_NAME, new org.apache.thrift.meta_data.FieldMetaData("firstName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SECOND_NAME, new org.apache.thrift.meta_data.FieldMetaData("secondName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NUMBER_COURSE, new org.apache.thrift.meta_data.FieldMetaData("numberCourse", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.NUMBER_GROUP, new org.apache.thrift.meta_data.FieldMetaData("numberGroup", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Student.class, metaDataMap);
  }

  public Student() {
  }

  public Student(
    java.lang.String firstName,
    java.lang.String secondName,
    long numberCourse,
    long numberGroup)
  {
    this();
    this.firstName = firstName;
    this.secondName = secondName;
    this.numberCourse = numberCourse;
    setNumberCourseIsSet(true);
    this.numberGroup = numberGroup;
    setNumberGroupIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Student(Student other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetFirstName()) {
      this.firstName = other.firstName;
    }
    if (other.isSetSecondName()) {
      this.secondName = other.secondName;
    }
    this.numberCourse = other.numberCourse;
    this.numberGroup = other.numberGroup;
  }

  public Student deepCopy() {
    return new Student(this);
  }

  @Override
  public void clear() {
    this.firstName = null;
    this.secondName = null;
    setNumberCourseIsSet(false);
    this.numberCourse = 0;
    setNumberGroupIsSet(false);
    this.numberGroup = 0;
  }

  public java.lang.String getFirstName() {
    return this.firstName;
  }

  public Student setFirstName(java.lang.String firstName) {
    this.firstName = firstName;
    return this;
  }

  public void unsetFirstName() {
    this.firstName = null;
  }

  /** Returns true if field firstName is set (has been assigned a value) and false otherwise */
  public boolean isSetFirstName() {
    return this.firstName != null;
  }

  public void setFirstNameIsSet(boolean value) {
    if (!value) {
      this.firstName = null;
    }
  }

  public java.lang.String getSecondName() {
    return this.secondName;
  }

  public Student setSecondName(java.lang.String secondName) {
    this.secondName = secondName;
    return this;
  }

  public void unsetSecondName() {
    this.secondName = null;
  }

  /** Returns true if field secondName is set (has been assigned a value) and false otherwise */
  public boolean isSetSecondName() {
    return this.secondName != null;
  }

  public void setSecondNameIsSet(boolean value) {
    if (!value) {
      this.secondName = null;
    }
  }

  public long getNumberCourse() {
    return this.numberCourse;
  }

  public Student setNumberCourse(long numberCourse) {
    this.numberCourse = numberCourse;
    setNumberCourseIsSet(true);
    return this;
  }

  public void unsetNumberCourse() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NUMBERCOURSE_ISSET_ID);
  }

  /** Returns true if field numberCourse is set (has been assigned a value) and false otherwise */
  public boolean isSetNumberCourse() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NUMBERCOURSE_ISSET_ID);
  }

  public void setNumberCourseIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NUMBERCOURSE_ISSET_ID, value);
  }

  public long getNumberGroup() {
    return this.numberGroup;
  }

  public Student setNumberGroup(long numberGroup) {
    this.numberGroup = numberGroup;
    setNumberGroupIsSet(true);
    return this;
  }

  public void unsetNumberGroup() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NUMBERGROUP_ISSET_ID);
  }

  /** Returns true if field numberGroup is set (has been assigned a value) and false otherwise */
  public boolean isSetNumberGroup() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NUMBERGROUP_ISSET_ID);
  }

  public void setNumberGroupIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NUMBERGROUP_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case FIRST_NAME:
      if (value == null) {
        unsetFirstName();
      } else {
        setFirstName((java.lang.String)value);
      }
      break;

    case SECOND_NAME:
      if (value == null) {
        unsetSecondName();
      } else {
        setSecondName((java.lang.String)value);
      }
      break;

    case NUMBER_COURSE:
      if (value == null) {
        unsetNumberCourse();
      } else {
        setNumberCourse((java.lang.Long)value);
      }
      break;

    case NUMBER_GROUP:
      if (value == null) {
        unsetNumberGroup();
      } else {
        setNumberGroup((java.lang.Long)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case FIRST_NAME:
      return getFirstName();

    case SECOND_NAME:
      return getSecondName();

    case NUMBER_COURSE:
      return getNumberCourse();

    case NUMBER_GROUP:
      return getNumberGroup();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case FIRST_NAME:
      return isSetFirstName();
    case SECOND_NAME:
      return isSetSecondName();
    case NUMBER_COURSE:
      return isSetNumberCourse();
    case NUMBER_GROUP:
      return isSetNumberGroup();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Student)
      return this.equals((Student)that);
    return false;
  }

  public boolean equals(Student that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_firstName = true && this.isSetFirstName();
    boolean that_present_firstName = true && that.isSetFirstName();
    if (this_present_firstName || that_present_firstName) {
      if (!(this_present_firstName && that_present_firstName))
        return false;
      if (!this.firstName.equals(that.firstName))
        return false;
    }

    boolean this_present_secondName = true && this.isSetSecondName();
    boolean that_present_secondName = true && that.isSetSecondName();
    if (this_present_secondName || that_present_secondName) {
      if (!(this_present_secondName && that_present_secondName))
        return false;
      if (!this.secondName.equals(that.secondName))
        return false;
    }

    boolean this_present_numberCourse = true;
    boolean that_present_numberCourse = true;
    if (this_present_numberCourse || that_present_numberCourse) {
      if (!(this_present_numberCourse && that_present_numberCourse))
        return false;
      if (this.numberCourse != that.numberCourse)
        return false;
    }

    boolean this_present_numberGroup = true;
    boolean that_present_numberGroup = true;
    if (this_present_numberGroup || that_present_numberGroup) {
      if (!(this_present_numberGroup && that_present_numberGroup))
        return false;
      if (this.numberGroup != that.numberGroup)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetFirstName()) ? 131071 : 524287);
    if (isSetFirstName())
      hashCode = hashCode * 8191 + firstName.hashCode();

    hashCode = hashCode * 8191 + ((isSetSecondName()) ? 131071 : 524287);
    if (isSetSecondName())
      hashCode = hashCode * 8191 + secondName.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(numberCourse);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(numberGroup);

    return hashCode;
  }

  @Override
  public int compareTo(Student other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetFirstName()).compareTo(other.isSetFirstName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFirstName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.firstName, other.firstName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSecondName()).compareTo(other.isSetSecondName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSecondName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.secondName, other.secondName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNumberCourse()).compareTo(other.isSetNumberCourse());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNumberCourse()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.numberCourse, other.numberCourse);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNumberGroup()).compareTo(other.isSetNumberGroup());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNumberGroup()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.numberGroup, other.numberGroup);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Student(");
    boolean first = true;

    sb.append("firstName:");
    if (this.firstName == null) {
      sb.append("null");
    } else {
      sb.append(this.firstName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("secondName:");
    if (this.secondName == null) {
      sb.append("null");
    } else {
      sb.append(this.secondName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("numberCourse:");
    sb.append(this.numberCourse);
    first = false;
    if (!first) sb.append(", ");
    sb.append("numberGroup:");
    sb.append(this.numberGroup);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class StudentStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public StudentStandardScheme getScheme() {
      return new StudentStandardScheme();
    }
  }

  private static class StudentStandardScheme extends org.apache.thrift.scheme.StandardScheme<Student> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Student struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FIRST_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.firstName = iprot.readString();
              struct.setFirstNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SECOND_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.secondName = iprot.readString();
              struct.setSecondNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // NUMBER_COURSE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.numberCourse = iprot.readI64();
              struct.setNumberCourseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // NUMBER_GROUP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.numberGroup = iprot.readI64();
              struct.setNumberGroupIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Student struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.firstName != null) {
        oprot.writeFieldBegin(FIRST_NAME_FIELD_DESC);
        oprot.writeString(struct.firstName);
        oprot.writeFieldEnd();
      }
      if (struct.secondName != null) {
        oprot.writeFieldBegin(SECOND_NAME_FIELD_DESC);
        oprot.writeString(struct.secondName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(NUMBER_COURSE_FIELD_DESC);
      oprot.writeI64(struct.numberCourse);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NUMBER_GROUP_FIELD_DESC);
      oprot.writeI64(struct.numberGroup);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class StudentTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public StudentTupleScheme getScheme() {
      return new StudentTupleScheme();
    }
  }

  private static class StudentTupleScheme extends org.apache.thrift.scheme.TupleScheme<Student> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Student struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetFirstName()) {
        optionals.set(0);
      }
      if (struct.isSetSecondName()) {
        optionals.set(1);
      }
      if (struct.isSetNumberCourse()) {
        optionals.set(2);
      }
      if (struct.isSetNumberGroup()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetFirstName()) {
        oprot.writeString(struct.firstName);
      }
      if (struct.isSetSecondName()) {
        oprot.writeString(struct.secondName);
      }
      if (struct.isSetNumberCourse()) {
        oprot.writeI64(struct.numberCourse);
      }
      if (struct.isSetNumberGroup()) {
        oprot.writeI64(struct.numberGroup);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Student struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.firstName = iprot.readString();
        struct.setFirstNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.secondName = iprot.readString();
        struct.setSecondNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.numberCourse = iprot.readI64();
        struct.setNumberCourseIsSet(true);
      }
      if (incoming.get(3)) {
        struct.numberGroup = iprot.readI64();
        struct.setNumberGroupIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

